// autoTherm 
export const SET_PAGE = 'SET_PAGE';
export const SET_PROG = 'SET_PROG';
export const SET_DEVICES = 'SET_DEVICES';
export const SET_PREFERRED_DEVICE = 'SET_PREFERRED_DEVICE';
export const UNSET_AUTOTHERM = 'UNSET_AUTOTHERM';
// patient
export const SET_PATIENT_NAME = 'SET_PATIENT_NAME';
export const SET_PATIENT_ID = 'SET_PATIENT_ID';
export const SET_PATIENT_GENDER = 'SET_PATIENT_GENDER';
export const SET_PATIENT_AGE = 'SET_PATIENT_AGE';
export const SET_PATIENT_DOP = 'SET_PATIENT_DOP';
export const SET_PATIENT_VAS_VALUE_AVG = 'SET_PATIENT_VAS_VALUE_AVG';
export const SET_PATIENT_VAS_VALUE_MIN = 'SET_PATIENT_VAS_VALUE_MIN';
export const SET_PATIENT_VAS_VALUE_MAX = 'SET_PATIENT_VAS_VALUE_MAX';
export const SET_PATIENT_SD = 'SET_PATIENT_SD';
export const SET_PATIENT_POST_FEELINGS = 'SET_PATIENT_POST_FEELINGS';
export const UNSET_PATIENT = 'UNSET_PATIENT';
// therapy
export const SET_THERAPY_TEMPERATURE = 'SET_THERAPY_TEMPERATURE';
export const SET_THERAPY_DURATION = 'SET_THERAPY_DURATION';
export const UNSET_THERAPY = 'UNSET_THERAPY';
export const SET_CURRENT_TEMPERATURE = 'SET_CURRENT_TEMPERATURE';


